apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: opensearch  # Change if using a different namespace
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
