apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc 
  labels:
    app: mongodb
    type: data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust size as needed
