apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:4
        imagePullPolicy: Never
        ports:
        - containerPort: 9042
        env:
        - name: MAX_HEAP_SIZE
          value: "1024M"
        - name: HEAP_NEWSIZE
          value: "1024M"
        - name: CASSANDRA_CLUSTER_NAME
          value: "TheHive"
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
      volumes:
      - name: cassandra-data
        persistentVolumeClaim:
          claimName: cassandra-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  ports:
  - protocol: TCP
    port: 9042
    targetPort: 9042
    nodePort: 30042
  type: NodePort
