apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels: 
    app: postgres
spec:
  storageClassName: standart
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: opensearch
    name: postgres-pvc

  hostPath:
    path: /home/kube/data/postgres
