apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: opensearch
spec:
  storageClassName: standart
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
