apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-conf
  namespace: opensearch
data:
  config.yaml: |
        rules_folder: rules
        scan_subdirectories: False
        run_every:
          minutes: 1440
        buffer_time:
          minutes: 15
        es_host: 10.10.8.80
        es_port: 31679
        es_username: "admin"
        es_password: "SecretPassword"
        use_ssl: True
        verify_certs: False
        es_ca_certs: "/home/kube/wazuh-kubernetes/wazuh/certs/indexer_cluster/root-ca.pem"
        writeback_index: elastalert_status
        writeback_alias: elastalert_alerts
        alert_time_limit:
          days: 2
