apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "mkdir -p /usr/share/elasticsearch/data/nodes && chown -R root:root /usr/share/elasticsearch/data && chmod -R 777 /usr/share/elasticsearch/data"]

        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        imagePullPolicy: Never
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms1024m -Xmx1024m"
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30200  # Specify the nodePort if you want a fixed port (optional)
  type: NodePort
