# PersistentVolumeClaim for SSA Data 1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssa-data1
  labels: 
    app: ssa
    volume: data1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi

---
# PersistentVolumeClaim for SSA Data 2
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssa-data2
  labels:
    app: ssa
    volume: data2
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi

---
# PersistentVolumeClaim for SSA Data 3
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssa-data3
  labels: 
    app: ssa
    volume: data3
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
