# PersistentVolumeClaim for Cassandra
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  labels: 
    app: cassandra
    type: data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
# PersistentVolumeClaim for Elasticsearch
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  labels: 
    app: elasticsearch
    type: data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
# PersistentVolumeClaim for Minio
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  labels: 
    app: minio
    type: data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
