apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: filestream
      enabled: true
      paths:
        - /var/log/suricata/eve.json

    output.logstash:
      hosts: ["ssa-logparser.opensearch.svc.cluster.local:5100"]
