apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ssa-node
  namespace: opensearch
spec:
  serviceName: ssa-node
  replicas: 3
  selector:
    matchLabels:
      app: ssa-node
  template:
    metadata:
      labels:
        app: ssa-node
    spec:
      containers:
      - name: ssa-node
        image: opensearchproject/opensearch:2.15.0
        ports:
        - containerPort: 10200  # HTTP Port 
        - containerPort: 10600  # Transport Port
        resources:
          limits:
            memory: "16Gi"
            cpu: "4"
          requests:
            memory: "8Gi"
            cpu: "2"
        env:
        - name: cluster.name
          value: ssa-cluster
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: ssa-node-0.ssa-node,ssa-node-1.ssa-node,ssa-node-2.ssa-node
        - name: cluster.initial_cluster_manager_nodes
          value: ssa-node-0,ssa-node-1,ssa-node-2
        - name: bootstrap.memory_lock
          value: "false"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms4g -Xmx4g -Dlog4j2.formatMsgNoLookups=true"
        volumeMounts:
        - mountPath: /usr/share/opensearch/config
          name: config-volume
        - mountPath: /usr/share/ssa/data
          name: data-volume
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
      volumes:
      - name: config-volume
        hostPath:
          path: /home/kube/docker/ssa/config
          type: Directory
      - name: data-volume
        persistentVolumeClaim:
          claimName: ssa-data1
---
apiVersion: v1
kind: Service
metadata:
  name: ssa-node
  namespace: opensearch
spec:
  clusterIP: None
  selector:
    app: ssa-node
  ports:
    - name: http
      port: 10200
      targetPort: 10200
    - name: transport
      port: 10600
      targetPort: 10600
---

apiVersion: v1
kind: Service
metadata:
  name: ssa-node-external
  namespace: opensearch
spec:
  type: NodePort
  selector:
    app: ssa-node
  ports:
    - name: http
      port: 10200
      targetPort: 10200
      nodePort: 30080
    - name: transport
      port: 10600
      targetPort: 10600
      nodePort: 30081
